# Используем Python 3.11
FROM python:3.11

WORKDIR /app

COPY app/ /app/
COPY requirements.txt /app/

RUN pip install --no-cache-dir -r /app/requirements.txt

# Запускаем инициализацию БД перед стартом сервера
CMD ["sh", "-c", "python init_db.py && uvicorn api:app --host 0.0.0.0 --port 8000"]
